#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sun Feb 12 17:29:05 2017

@author: ceciliaLee
"""
def label_mapping():
    f = open('/Users/ceciliaLee/Desktop/Windows/csv/malware_naming.csv')
    classes=[]
    map_dict = {}

    for i in f.readlines()[1:]:
        classes.append(i.split(',')[0])
        index=[i for i in range(len(set(classes)))]

    for i in range(len(set(classes))):
        map_dict[list(set(classes))[i]]=index[i]

  #  print len(classes)  # 17267
  #  print len(set(classes)) # 40 
    return map_dict




if __name__ == '__main__':
    map_dict = label_mapping()
    print map_dict
    
    